version: "3.1"

services:
  api-runner:
    image: api-tests
    container_name: api-supertest-runner
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    stdin_open: true  